# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('playing_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ownedGames',
            field=models.ManyToManyField(blank=True, default=None, to='playing_area.Game'),
        ),
    ]
