# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 21:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('url', models.URLField(max_length=150)),
                ('price', models.FloatField(default=0)),
                ('image_url', models.URLField(default='', max_length=150)),
                ('genre', models.CharField(default='Other', max_length=15)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('purchased_times', models.IntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.FloatField(default=0)),
                ('gameState', models.CharField(default='', max_length=1500)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameid', to='playing_area.Game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
