# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 23:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playing_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.FloatField(default=0)),
                ('gameState', models.CharField(max_length=1500)),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='game',
        ),
        migrations.RemoveField(
            model_name='state',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='author',
        ),
        migrations.AddField(
            model_name='game',
            name='game_version',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='ot', max_length=2),
        ),
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_id', to='playing_area.Game'),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
