# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playing_area', '0002_auto_20170410_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_version',
        ),
    ]
