# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playing_area', '0003_remove_game_game_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Other', max_length=15),
        ),
    ]
