# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import purchase.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('playing_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.FloatField(default=0)),
                ('orderDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('orderDateYearMonthDay', models.CharField(default=purchase.models.get_default_ymd, max_length=8)),
                ('paymentDate', models.DateTimeField(default=None, null=True)),
                ('paymentRef', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('_games', models.ManyToManyField(blank=True, default=None, to='playing_area.Game')),
                ('_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile')),
            ],
        ),
    ]
